# Generated by Django 6.0.4 on 2026-05-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prompt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.prompt'),
        ),
    ]
